# This is a template you can use as a starting point for developing your CI-CD pipeline.
# It won't work out of the box. Some things might in the wrong order or missing.
# You might also have to make changes other files in this repo to make it work.
#
# Along the way, you'll also find some prompts for research and discussion.
#
# Uncomment the stuff below and play around with it!

# # Q: What is the effect of the the image keyword?
# image: node:12.14.1

# # Q: What do you think this section is for? What is it meant to achieve?
# # There is actually a piece missing from this file to fully make this work.
# # Do some research and discuss within your team. 
# services: 
#   - name: mongo:4.2

# # Q: And what about this section?
# # How does what we define in here relate to the section above?
# variables:
#   MONGODB_URL: "what/should/go/here?"

# test_unit:
#   script:
#     - npm run lint
#     - npm run test:unit
#     - npm install

# test_integration:
#   # Q: What is the effect of specifying an image here?
#   # Do some research and discuss within your team.
#   image: cypress/base:12.14.1
#   script:
#     - npm run test:integration
#     - npm install
#     # Q: What is the effect of the ampersand? Why do we need it?
#     - npm run start:ci &
