name: Build CI and Deploy
on:
  push:
    branches:
      - main  # Replace with the appropriate branch name

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name=mongodb
    env:
      MONGODB_URL: mongodb://localhost:27017/acebook_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use actions/checkout@v2 instead of v3
      - name: Set up Node.js
        uses: actions/setup-node@v2  # Use actions/setup-node@v2 instead of v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint and unit tests
        run: |
          npm run lint
          npm run test:unit
      - name: Run integration tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          start: npm run start:ci

  deploy:
    name: Deploy
    needs: build  # Ensure that the "build" job completes before deploying
    runs-on: ubuntu-latest
    steps:
      - name: List Repository Contents
        run: ls -R
      - name: Call a Bash Script
        run: |
          chmod +x ${GITHUB_WORKSPACE}/scripts/deploy-to-instance.sh
          bash ${GITHUB_WORKSPACE}/scripts/deploy-to-instance.sh
